apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbvue
  namespace: webapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hbvue
  template:
    metadata:
      labels:
        app: hbvue
    spec:
      containers:
      - name: hbvue
        image: lucarv/365vue:0.0.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hbvue-svc
  namespace: webapps
spec:
  selector:
    app: hbvue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hbvue-ing
  namespace: webapps
spec:
  ingressClassName: nginx
  rules:
    - host: gallery.hbvu.local
      http:
        paths:
          - path: /           
            pathType: Prefix
            backend:
              service:
                name: hbvue-svc
                port:
                  number: 80