apiVersion: v1
kind: Service
metadata:
  namespace: hbvu
  name: hbvue
spec:
  selector:
    app: xtr
  ports:
    - protocol: TCP
      port: 80
      name: http
  type: LoadBalancer    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbvue
  namespace: hbvu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hbvue
  template:
    metadata:
      labels:
        app: hbvue
    spec:
      containers:
      - name: hbvue
        image: lucarv/365vue:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hbvue-svc
  namespace: hbvu
spec:
  selector:
    app: hbvue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---

