---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: subsonic-nfs-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: subsonic-nfs
  nfs:
    server: 192.168.1.8
    path: /var/media/music/mp3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subsonic-music-pvc
  namespace: subsonic
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: subsonic-nfs
  resources:
    requests:
      storage: 500Gi