apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: data
type: Opaque
data:
  POSTGRES_USER: bHVjYXJ2
  POSTGRES_PASSWORD: bHVjYVBXRDQxaWI0Mw==  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: librephotos-config
  namespace: librephotos
data:
  POSTGRES_DB: "librephotos"
  POSTGRES_HOST: "postgres.data.svc.cluster.local"  # Uses `data` namespace
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis.data.svc.cluster.local"  # Redis in `data` namespace
  REDIS_PORT: "6379"
  SECRET_KEY: "your-secret-key"
