---
# ConfigMap for libr-photos configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: libre-photos-config
  namespace: libre
data:
  # Basic configuration
  LIBR_SECRET_KEY: "canyoukeepasecret-orwillyoutell"
  DEBUG: "false"
  DISABLE_EXIF_THUMBNAIL: "false"
  MAPBOX_API_KEY: ""
  
  # Frontend configuration
  BACKEND_HOST: "http://libre-photos:8001"
  CSRF_TRUSTED_ORIGINS: "https://photos.hbvu.su"
  
  # Database configuration - using PostgreSQL
  DB_BACKEND: "postgresql"
  
  # Redis configuration - referencing existing service in data namespace
  REDIS_HOST: "redis.data.svc.cluster.local"
  REDIS_PORT: "6379"
---