---
# ConfigMap for libr-photos configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: libre-photos-config
  namespace: libre
data:
  # Basic configuration
  SECRET_KEY: "can-you-keep-a-secret-or-will-you-tell"
  DEBUG: "false"
  DISABLE_EXIF_THUMBNAIL: "false"
  
  # Frontend configuration
  BACKEND_HOST: "http://libre-photos-backend:8000"
  
  # Database configuration - using PostgreSQL
  DB_BACKEND: "postgresql"
  
  # Redis configuration
  REDIS_HOST: "redis.data.svc.cluster.local"
  REDIS_PORT: "6379"
  
  # Web server configuration
  ALLOWED_HOSTS: "libre-photos-frontend,libre-photos-backend,localhost"
  CSRF_TRUSTED_ORIGINS: "https://photos.hbvu.su"