# Deployment for libre-photos
apiVersion: apps/v1
kind: Deployment
metadata:
  name: libre-photos
  namespace: libre
  labels:
    app: libre-photos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libre-photos
  template:
    metadata:
      labels:
        app: libre-photos
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: libre-photos
        image: reallibrephotos/librephotos
        ports:
        - containerPort: 3000
          name: frontend
        - containerPort: 8001
          name: backend
        envFrom:
        - configMapRef:
            name: libre-photos-config
        - secretRef:
            name: libre-photos-secret
        volumeMounts:
        - mountPath: /data
          name: libre-photos-data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /api/healthcheck/
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/healthcheck/
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 20
      volumes:
      - name: libre-photos-data
        persistentVolumeClaim:
          claimName: libre-photos-data