---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: libre-photos-backend
  namespace: libre
  labels:
    app: libre-photos-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libre-photos-backend
  template:
    metadata:
      labels:
        app: libre-photos-backend
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: libre-photos-backend
        image: librephotos/backend:latest
        ports:
        - containerPort: 8000
          name: backend
        envFrom:
        - configMapRef:
            name: libre-photos-config
        - secretRef:
            name: libre-photos-secret
        volumeMounts:
        - mountPath: /data
          name: libre-photos-data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /api/healthcheck/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/healthcheck/
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 20
      volumes:
      - name: libre-photos-data
        persistentVolumeClaim:
          claimName: libre-photos-data
---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: libre-photos-frontend
  namespace: libre
  labels:
    app: libre-photos-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libre-photos-frontend
  template:
    metadata:
      labels:
        app: libre-photos-frontend
    spec:
      containers:
      - name: libre-photos-frontend
        image: librephotos/frontend:latest
        ports:
        - containerPort: 3000
          name: frontend
        env:
        - name: BACKEND_HOST
          valueFrom:
            configMapKeyRef:
              name: libre-photos-config
              key: BACKEND_HOST
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes: []
---