# Secret for sensitive information
apiVersion: v1
kind: Secret
metadata:
  name: libre-photos-secret
  namespace: libre
type: Opaque
stringData:
  # Replace with your actual credentials
  ADMIN_EMAIL: "root@hbvu.su"
  ADMIN_USERNAME: "lucarv"
  ADMIN_PASSWORD: "lucaPWD41ib43"
  
  # PostgreSQL credentials - referencing existing service in data namespace
  DB_HOST: "postgres.data.svc.cluster.local"
  DB_NAME: "librephotos"
  DB_USER: "lucarv"
  DB_PASS: "lucaPWD41ib43"
  DB_PORT: "5432"
  
  # Redis password if needed
  REDIS_PASSWORD: ""