---
# PersistentVolume for NFS storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: libre-photos-nfspv
spec:
  capacity:
    storage: 1000Gi  # Adjust based on your NFS storage capacity
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: mjolnir  # Replace with your NFS server IP
    path: /mnt/ext/2T/k3s-data/libre  # Path to your NFS export
---
# PersistentVolumeClaim for NFS storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: libre-photos-data
  namespace: libre
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi  # Adjust based on your needs
  storageClassName: ""
  volumeName: libre-photos-nfspv
