apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: influxdb
  name: influxdb
  namespace: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      component: influxdb
  template:
    metadata:
      labels:
        component: influxdb
    spec:
      containers:
      - image: docker.io/influxdb:2.6-alpine
        imagePullPolicy: IfNotPresent
        name: influxdb
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"        
        envFrom:
        - secretRef:
           name: influxdb-creds
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: var-lib-influxdb    
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: var-lib-influxdb
        persistentVolumeClaim:
          claimName: influxdb-claim
