apiVersion: v1
kind: Service
metadata:
  labels:
    component: influxdb
  name: influxdb
  namespace: influxdb
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    component: influxdb
  type: NodePort
