apiVersion: v1
kind: PersistentVolume
metadata:
  name: gonic-music-pv
spec:
  storageClassName: ""
  capacity:
    storage: 500Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.8
    path: /var/lib/media/music/mp3