apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gonic-music-pvc
  namespace: gonic
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 500Gi
  volumeName: gonic-music-pv