apiVersion: v1
kind: PersistentVolume
metadata:
  name: xtr-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.8
    path: "/var/media/web/xtr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xtr-files
  namespace: hbvu
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: xtr-pv
---

apiVersion: v1
kind: Service
metadata:
  namespace: hbvu
  name: xtr
spec:
  selector:
    app: xtr
  ports:
    - protocol: TCP
      port: 80
      name: http
  type: LoadBalancer    
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hbvu
  name: xtr
  labels:
    app: xtr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xtr
  template:
    metadata:
      labels:
        app: xtr
    spec:    
      containers:
      - name: xtr
        image: nginx
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"        
        ports:
          - containerPort: 80
            name: "xtr"
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: nginx-storage
      volumes:
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: xtr-files
