apiVersion: v1
kind: PersistentVolume
metadata:
  name: spc.eu-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.8
    path: "/var/media/web/spc.eu/public_html"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spc.eu-files
  namespace: hbvu
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: spc.eu-pv