---
apiVersion: v1
kind: Service
metadata:
  namespace: webapps
  name: blogt-frontend
spec:
  selector:
    app: blogt-frontend
  ports:
    - protocol: TCP
      port: 80
      name: http
  type: LoadBalancer
  externalTrafficPolicy: Local 
  loadBalancerIP: 192.168.1.204  