---
apiVersion: v1
kind: Service
metadata:
  namespace: webapps
  name: blogt-api
spec:
  selector:
    app: blogt-api
  ports:
    - protocol: TCP
      port: 3000
      name: http
  type: LoadBalancer
  externalTrafficPolicy: Local 
  loadBalancerIP: 192.168.1.202
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: webapps
  name: blogt-api
  labels:
    app: blogt-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogt-api
  template:
    metadata:
      labels:
        app: blogt-api
    spec:
      securityContext:
        runAsUser: 1000 
        runAsGroup: 1000
        fsGroup: 1000
        allowPrivilegeEscalation: false
      containers:
        - name: blogt-api
          image: lucarv/blogt-api:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi" 
              cpu: "500m" 
          ports:
            - containerPort: 80
              name: blogt-api
          volumeMounts:
            - name: blogposts
              mountPath: /usr/src/app/posts
      volumes:
        - name: blogposts
          persistentVolumeClaim:
            claimName: blog-nfspvc
