apiVersion: v1
kind: Secret
metadata:
  name: guacamole-db
  namespace: guacamole
type: Opaque
stringData:
  hostname: "192.168.1.8"
  database: "guacamole_db"
  username: "guacamole_user"
  password: "7mileshi"
