---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs/2000/minio
    server: elite
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs-pvc
  namespace: minio
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: minio-nfs-pv
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
type: Opaque
data:
  root-user: bHVjYXJ2
  root-password: bHVjYVBXRCRNaW5JMA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2023-10-07T15-07-38Z
          args:
            - server
            - /data
            - --console-address=:9001
          ports:
            - containerPort: 9000
              name: minio-port  # Add this line
            - containerPort: 9001
              name: console-port  # Add this line
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-password
          volumeMounts:
              - name: minio-nfs-storage
                mountPath: /data
          volumes:
            - name: minio-nfs-storage
              persistentVolumeClaim:
                claimName: minio-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio
spec:
  type: LoadBalancer
  ports:
    - name: s3-api # Name for the S3 API port in the service
      port: 9000
      targetPort: minio-port # Reference to the container port by name
    - name: console # Name for the console port in the service
      port: 9001
      targetPort: console-port # Reference to the console port by name
  selector:
    app: minio
---