apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: data
type: Opaque
data:
  POSTGRES_USER: bHVjYXJ2
  POSTGRES_PASSWORD: bHVjYVBXRDRwMHN0ZzQzcw==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: data  # Change as needed
data:
  POSTGRES_DB: "postgres"  # The default database name
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
