# Create a ConfigMap for PostgreSQL configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: data
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  # Additional PostgreSQL configuration can be added here
---
# Create a Secret for the PostgreSQL password
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: data
type: Opaque
data:
  # This is "postgres" encoded in base64, you should change this to a secure password
  postgres-password: bHVjYVBXRAo=
