apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: nfs
    app: postgres  
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/ext/2T/k3s-data/pg
    server: mjolnir
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: data
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      type: nfs
      app: postgres    
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs     
  volumeName: postgres-pv
