---
# Create a PersistentVolume that points to your NFS server
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: nfs
    app: postgres
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: mjolnir
    path: /mnt/ext/2T/pg
---
# Create a PersistentVolumeClaim to use the PV
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      type: nfs
      app: postgres
---