apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
  namespace: libre
spec:
  containers:
  - name: postgres-client
    image: postgres:latest
    command: ["sleep", "3600"] # Keeps the pod running for testing
    env:
    - name: PGHOST
      value: "postgres-service.data.svc.cluster.local" # Replace with your PostgreSQL service's FQDN
    - name: PGUSER
      value: "lucarv" # Replace with your PostgreSQL username
    - name: PGPASSWORD
      value: "lucaPWD4p0stg43s" # Replace with your PostgreSQL password
  restartPolicy: Always
