apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: photos
data:
  DB_HOSTNAME: "postgresql.data.svc.cluster.local"
  DB_PORT: "5432"
  DB_DATABASE_NAME: "immich_db"
  REDIS_HOSTNAME: "redis.data.svc.cluster.local"
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
  namespace: photos
type: Opaque
data:
  DB_USERNAME: aW1taWNo
  DB_PASSWORD: aW1taWNoUFdENGltbWljaA==
