---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
type: Opaque
data:
  root-user: bHVjYXJ2
  root-password: bHVjYVBXRCRNaW5JMA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2023-10-07T15-07-38Z
          args:
            - server
            - /data
            - --console-address=:9001
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-password
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio
spec:
  type: LoadBalancer
  ports:
    - name: s3-api # Name for the S3 API port in the service
      port: 9000
      targetPort: minio-port # Reference to the container port by name
    - name: console # Name for the console port in the service
      port: 9001
      targetPort: console-port # Reference to the console port by name
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-nodeport-service
  namespace: minio
spec:
  type: NodePort
  ports:
    - port: 9000     # MinIO port
      targetPort: 9000
      nodePort: 30001  # This will be the port exposed on the node (choose a port between 30000-32767)
    - port: 9001     # MinIO console port (if needed)
      targetPort: 9001
      nodePort: 30002  # Same for the console, if you need it
  selector:
    app: minio
