apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfspv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/usb/500/minio
    server: ubumac
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfspvc
  namespace: minio
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: minio-nfspv
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
type: Opaque
data:
  root-user: bHVjYXJ2
  root-password: bHVjYVBXRCRNaW5JMA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2023-10-07T15-07-38Z
          args:
            - server
            - /data
            - --console-address=:9001
          ports:
            - containerPort: 9000
              name: minio-port
            - containerPort: 9001
              name: console-port
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-password
            - name: MINIO_API_REQUEST_SIZE
              value: "1073741824"  # 1GB in bytes
            - name: MINIO_BROWSER_UPLOAD_SIZE_LIMIT
              value: "5368709120"  # 5GB in bytes
            - name: MINIO_DISK_USAGE_CRAWL_DELAY
              value: "10"
            - name: MINIO_DISK_USAGE_CRAWL_CYCLE
              value: "24h"
            - name: MINIO_API_CONCURRENT_REQUESTS
              value: "100"
            - name: MINIO_CACHE_EXPIRY
              value: "72h"
          volumeMounts:
            - name: 500-store
              mountPath: /data
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
      volumes:
        - name: 500-store
          persistentVolumeClaim:
            claimName: minio-nfspvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio
spec:
  type: LoadBalancer
  ports:
    - name: s3-api
      port: 9000
      targetPort: minio-port
    - name: console
      port: 9001
      targetPort: console-port
  selector:
    app: minio