apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: apps-backend
spec:
  ports:
    - port: 9000
      targetPort: 9000
      name: minio
    - port: 9001
      targetPort: 9001
      name: console
  selector:
    app: minio
  type:
    LoadBalancer  