---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.200  
  ports:
    - name: s3-api
      port: 9000
      targetPort: minio-port
    - name: console
      port: 9001
      targetPort: console-port
  selector:
    app: minio