apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfspv
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/usb/500/minio
    server: ubumac
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfspvc
  namespace: minio
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: ""
  volumeName: minio-nfspv