---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jellyfin-config
  namespace: jellyfin
data:
  system.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <ServerConfiguration>
      <System>
        <PublicPort>8096</PublicPort>
        <EnableHttps>false</EnableHttps>
        <PreferredLanguage>en</PreferredLanguage>
      </System>
    </ServerConfiguration>
  users.xml: |
    <Users>
      <User>
        <Name>admin</Name>
        <Id>1</Id>
        <Policy>
          <IsAdministrator>true</IsAdministrator>
        </Policy>
      </User>
    </Users>
---
apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-user-credentials
  namespace: jellyfin
type: Opaque
data:
  admin-password: bHVjYVBXRCRqMzExIWYhbg==