---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-nfspv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/usb/500/music
    server: elite
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-nfspvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: jellyfin-nfspv
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jellyfin-config
  namespace: jellyfin
data:
  system.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <ServerConfiguration>
      <System>
        <PublicPort>8096</PublicPort>
        <EnableHttps>false</EnableHttps>
        <PreferredLanguage>en</PreferredLanguage>
      </System>
    </ServerConfiguration>
  users.xml: |
    <Users>
      <User>
        <Name>admin</Name>
        <Id>1</Id>
        <Policy>
          <IsAdministrator>true</IsAdministrator>
        </Policy>
      </User>
    </Users>
---
apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-user-credentials
  namespace: jellyfin
type: Opaque
data:
  admin-password: bXlzZWN1cmVwYXNzd29yZA== # Base64 encoded for "mysecurepassword"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          ports:
            - containerPort: 8096
              name: http
            - containerPort: 8920
              name: https
          env:
            - name: JELLYFIN_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jellyfin-user-credentials
                  key: admin-password
          volumeMounts:
            - name: media
              mountPath: /media
            - name: config
              mountPath: /config
            - name: jellyfin-secret
              mountPath: /config/secret
              subPath: admin-password
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: jellyfin-nfspvc
        - name: config
          configMap:
            name: jellyfin-config
        - name: jellyfin-secret
          secret:
            secretName: jellyfin-user-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  namespace: jellyfin
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8096
      targetPort: 8096
    - name: https
      port: 8920
      targetPort: 8920
  selector:
    app: jellyfin
