---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-nfspv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/usb/500/music  # This will hold your media files
    server: elite
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-nfspvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: jellyfin-nfspv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-nfspv
spec:
  capacity:
    storage: 5Gi  # You can adjust this size based on your needs
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/usb/500/music/jellyfin-config  # Change this path as needed for configuration
    server: elite
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-nfspvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi  # Match the size of the PV above
  storageClassName: ""
  volumeName: jellyfin-config-nfspv