apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: mqtt
spec:
  selector:
    matchLabels:
      component: mosquitto
  template:
    metadata:
      labels:
        component: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: lucarv/mosquitto
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 1883