kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-claim
  namespace: mqtt
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
