apiVersion: v1
kind: PersistentVolume
metadata:
  name: cocobox-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.8
    path: "/var/media/web"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-hbvu-files
  namespace: hbvu
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: cocobox-pv