apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-client
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-client
  template:
    metadata:
      labels:
        app: minio-client
    spec:
      containers:
      - name: minio-client
        image: minio/minio:RELEASE.2023-10-07T15-07-38Z
        command: ["sh", "-c", "tail -f /dev/null"]