---
apiVersion: v1
kind: Service
metadata:
  namespace: webapps
  name: blotpix2minio
spec:
  selector:
    app: blotpix2minio
  ports:
    - protocol: TCP
      port: 3000
      name: http
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: webapps
  name: blotpix2minio
  labels:
    app: blotpix2minio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blotpix2minio
  template:
    metadata:
      labels:
        app: blotpix2minio
    spec:
      containers:
      - name: blotpix2minio
        image: lucarv/blotupl4:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 3000
            name: blotpix2minio