---
apiVersion: v1
kind: Service
metadata:
  namespace: webapps
  name: blogt-editor
spec:
  selector:
    app: blogt-editor
  ports:
    - protocol: TCP
      port: 3000
      name: http
  type: LoadBalancer
  externalTrafficPolicy: Local 
  loadBalancerIP: 192.168.1.203
