apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: webapps
  name: blogt-editor
  labels:
    app: blogt-editor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogt-editor
  template:
    metadata:
      labels:
        app: blogt-editor
    spec:
      containers:
        - name: blogt-editor
          image: lucarv/blogt-editor:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi" 
              cpu: "500m" 
          ports:
            - containerPort: 80
              name: blogt
          env:
            - name: EDITOR_USERNAME
              valueFrom:
                secretKeyRef:
                  name: editor-credentials
                  key: accessKey
            - name: EDITOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: editor-credentials
                  key: secretKey
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: editor-credentials
                  key: sessionSecret      
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: accessKey                              
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: secretKey
            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: endpoint
            - name: MINIO_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: minioServiceURL
            - name: BLOGT_EDITOR_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: blogtEditorServiceName
          volumeMounts:
            - name: blogposts
              mountPath: /app/posts
      volumes:
        - name: blogposts
          persistentVolumeClaim:
            claimName: blog-nfspvc
