apiVersion: v1
kind: Secret
metadata:
  namespace: webapps
  name: minio-credentials
type: Opaque
stringData:
  accessKey: lucarv
  secretKey: lucaPWD$MinI0
  endpoint: minio-service.minio.svc.cluster.local
---
apiVersion: v1
kind: Secret
metadata:
  namespace: webapps
  name: editor-credentials
type: Opaque
stringData:
  accessKey: lucarv
  secretKey: lucaPWD$b10gt
  sessionSecret: YV92ZXJ5X2xvbmdfcmFuZG9tX3N0cmluZ191c2VkX3RvX3Byb3RlY3RfYmxvZ3RfZWRpdG9y
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: webapps
  name: app-config
data:
  minioServiceURL: minio-service.minio.svc.cluster.local
  blogtEditorServiceName: blogt-editor
