---
apiVersion: v1
kind: Secret
metadata:
  namespace: webapps
  name: minio-credentials
type: Opaque
stringData:
  accessKey: lucarv
  secretKey: lucaPWD$MinI0
  endpoint: minio-service.minio.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  namespace: webapps
  name: blotpix-be
spec:
  selector:
    app: blotpix-be
  ports:
    - protocol: TCP
      port: 80
      name: http
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: webapps
  name: blotpix-be
  labels:
    app: blotpix-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blotpix-be
  template:
    metadata:
      labels:
        app: blotpix-be
    spec:
      containers:
      - name: blotpix-be
        image: lucarv/blotupl4:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
            name: blotpix-be
        env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: accessKey
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: secretKey
          - name: MINIO_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: endpoint