---
apiVersion: v1
kind: Service
metadata:
  namespace: webapps
  name: blotpix-fe
spec:
  selector:
    app: blotpix-fe
  ports:
    - protocol: TCP
      port: 80
      name: http
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: webapps
  name: blotpix-fe
  labels:
    app: blotpix-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blotpix-fe
  template:
    metadata:
      labels:
        app: blotpix-fe
    spec:
      containers:
      - name: blotpix-fe
        image: lucarv/blotupl4_fe:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
            name: blotpix-fe