apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: blogt-hpa
  namespace: webapps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blogt
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80  # Scale to maintain 80% CPU usage
