---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: minio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minio-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio-server
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args:
        - minio server /data --console-address :9090 --address :9000
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              key: MINIO_ROOT_USER
              name: minio-secrets
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MINIO_ROOT_PASSWORD
              name: minio-secrets         
        volumeMounts:
        - name: storage
          mountPath: "/data"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-nfs-pvc
        - name: nfs-storage
          hostPath:
            path: /var/media/minio-ccb                  
