---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: minio
type: Opaque
data:
  MINIO_ROOT_USER: bHVjYXJ2
  MINIO_ROOT_PASSWORD: bHVjYVBXRCRNaW5JMA==
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-nfs
provisioner: nfs-client
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs-pv
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minio-nfs
  nfs:
    path: /var/media/minio-ccb
    server: 192.168.1.8
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs-pvc
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minio-nfs
  resources:
    requests:
      storage: 250Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: minio
  name: minio-service
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000
      name: http
      targetPort: 9000
  type: LoadBalancer   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: minio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args:
        - minio server /data --address :9000
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              key: MINIO_ROOT_USER
              name: minio-secrets
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MINIO_ROOT_PASSWORD
              name: minio-secrets         
        volumeMounts:
        - name: storage
          mountPath: "/data"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-nfs-pvc
        - name: nfs-storage
          hostPath:
            path: /var/media/minio-ccb                  
