---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-nfs
provisioner: nfs-client
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs-pv
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minio-nfs
  nfs:
    path: /var/media/minio-ccb
    server: 192.168.1.8
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs-pvc
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minio-nfs
  resources:
    requests:
      storage: 250Gi