---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: webapps
  name: blogt-frontend
  labels:
    app: blogt-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blogt-frontend
  template:
    metadata:
      labels:
        app: blogt-frontend
    spec:
      securityContext:
        runAsUser: 1000 
        runAsGroup: 1000
        fsGroup: 1000
        allowPrivilegeEscalation: false
      containers:
        - name: blogt-frontend
          image: lucarv/blogtv:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi" 
              cpu: "500m" 
          ports:
            - containerPort: 80
              name: blogt
          volumeMounts:
            - name: blogposts
              mountPath: /app/posts
      volumes:
        - name: blogposts
          persistentVolumeClaim:
            claimName: blog-nfspvc
      terminationGracePeriodSeconds: 30
      livenessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 60
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /readiness
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 30
        failureThreshold: 3
