---
apiVersion: v1
kind: Secret
metadata:
  namespace: webapps
  name: minio-credentials
type: Opaque
stringData:
  accessKey: lucarv
  secretKey: lucaPWD$MinI0
  endpoint: minio-service.minio.svc.cluster.local