apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: mariadb
  name: mariadb
spec:
  selector:
    matchLabels:
      component: mariadb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          ports:
            - containerPort: 3306
          args:
            - --transaction-isolation=READ-COMMITTED
            - --binlog-format=ROW
            - --max-connections=1000
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: mariadb-secrets
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mariadb-secrets
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: mariadb-secrets
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: mariadb-secrets
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: var-lib-mysql             
      restartPolicy: Always
      volumes:
      - name: var-lib-mariadb
        persistentVolumeClaim:
          claimName: mariadb-claim