apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-matching
  namespace: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-matching
  template:
    metadata:
      labels:
        app: temporal-matching
    spec:
      containers:
      - name: matching
        image: temporalio/server:1.22.4
        ports:
        - containerPort: 7235
        env:
        - name: SERVICES
          value: "matching"
        - name: LOG_LEVEL
          value: "info"
        - name: NUM_HISTORY_SHARDS
          value: "512"
        - name: DB
          value: "postgres12"
        - name: DBNAME
          valueFrom:
            secretKeyRef:
              name: temporal-db
              key: POSTGRES_DB
        - name: VISIBILITY_DBNAME
          valueFrom:
            secretKeyRef:
              name: temporal-db
              key: POSTGRES_VISIBILITY_DB
        - name: POSTGRES_SEEDS
          valueFrom:
            secretKeyRef:
              name: temporal-db
              key: POSTGRES_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: temporal-db
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: temporal-db
              key: POSTGRES_USER
        - name: POSTGRES_PWD
          valueFrom:
            secretKeyRef:
              name: temporal-db
              key: POSTGRES_PASSWORD
        - name: ENABLE_ES
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-matching
  namespace: temporal
spec:
  selector:
    app: temporal-matching
  ports:
  - port: 7235
    targetPort: 7235
  clusterIP: None