apiVersion: batch/v1
kind: Job
metadata:
  name: temporal-test
  namespace: temporal
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: test
        image: temporalio/admin-tools:1.22.4
        command: ["tctl"]
        args: ["--address", "temporal-frontend:7233", "cluster", "health"]