---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prism-config
  namespace: prism
data:
  PHOTOPRISM_SITE_URL: "https://prism.hbvu.su"
  PHOTOPRISM_ORIG_PATH: "/photoprism/originals"
  PHOTOPRISM_STORAGE_PATH: "/photoprism/storage"
  PHOTOPRISM_DISABLE_TLS: "false"
  PHOTOPRISM_DISABLE_SETTINGS: "false"
  PHOTOPRISM_DEFAULT_LOCALE: "en"
  PHOTOPRISM_DATABASE_DRIVER: "sqlite"
  PHOTOPRISM_READONLY: "false"
  PHOTOPRISM_TRUSTED_PROXIES: "172.16.0.0/12,192.168.0.0/16"
---
apiVersion: v1
kind: Secret
metadata:
  name: prism-secrets
  namespace: prism
type: Opaque
stringData:
  admin-password: "lucaPWD$p4ism"