# namespace.yaml
# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prism-config
  namespace: prism
data:
  prism_SITE_URL: "https://prism.hbvu.su"
  prism_ORIG_PATH: "/prism/originals"
  prism_STORAGE_PATH: "/prism/storage"
  prism_DISABLE_TLS: "false"
  prism_DISABLE_SETTINGS: "false"
  prism_DEFAULT_LOCALE: "en"
  prism_DATABASE_DRIVER: "sqlite"
  prism_READONLY: "false"
---
# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: prism-secrets
  namespace: prism
type: Opaque
stringData:
  admin-password: "lucaPWD$p4ism"  # Replace with your password
---
# persistent-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prism-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/usb/500/prism
    server: ubumac
---
# persistent-volume-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prism-pvc
  namespace: prism
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
---
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prism
  namespace: prism
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prism
  template:
    metadata:
      labels:
        app: prism
    spec:
      containers:
      - name: prism
        image: photoprism/photoprism:latest
        ports:
        - containerPort: 2342
        envFrom:
        - configMapRef:
            name: prism-config
        env:
        - name: PHOTOPRISM_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: prism-secrets
              key: admin-password
        volumeMounts:
        - name: photo-storage
          mountPath: /prism/originals
        - name: photo-storage
          mountPath: /prism/storage
      volumes:
      - name: photo-storage
        persistentVolumeClaim:
          claimName: prism-pvc
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prism
  namespace: prism
spec:
  selector:
    app: prism
  ports:
  - port: 2342
    targetPort: 2342
    protocol: TCP
  type: LoadBalancer