---
apiVersion: v1
kind: Service
metadata:
  name: prism
  namespace: prism
spec:
  selector:
    app: prism
  ports:
    - port: 2342
      targetPort: 2342
      protocol: TCP
  type: LoadBalancer
  externalTrafficPolicy: Local
 loadBalancerIP: 192.168.1.201