---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prism-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/usb/500/prism
    server: ubumac
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prism-pvc
  namespace: prism
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""