apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: nextcloud
  name: nextcloud
  namespace: nextcloud
spec:
  selector:
    matchLabels:
      component: nextcloud
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: nextcloud
    spec:
      containers:
        - image: qusp66/nextcloud
          imagePullPolicy: Always
          name: nextcloud
          resources:
            requests:
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"          
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: mariadbdb-secrets
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mariadbdb-secrets
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: mariadb-secrets
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-persistent-storage
      restartPolicy: Always
      volumes:
        - name: nextcloud-persistent-storage
          persistentVolumeClaim:
            claimName: nextcloud-pvc
