apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  namespace: nextcloud
type: Opaque
data:
  MYSQL_DATABASE: bmV4dGNsb3Vk  #nextcloud
  MYSQL_USER: bmV4dGNsb3Vk      #nextcloud
  MYSQL_PASSWORD: bHVjYVBXRDRtYTQxYURC
  MYSQL_ROOT_PASSWORD: bWFyaWFST09U